### PR TITLE
Added Time support

### PR DESCRIPTION
**Pull request by Zhomart**
Added couple of internal methods to parse time. Added necessary specs.

### CODE REVIEW

**Review by tbrand — CHANGES_REQUESTED** [review]
Thanks for this! Since I have no time to review now, let me check this after. :smile:

**Comment by tbrand** [comment]
Great commit!
Could you rename `_read_value` to `read_value` and `_to_db_value` to `to_db_value`?
Because I think we don't have name the method like that.

I will merge this after the changes:smile:

**Comment by Zhomart** [comment]
@tbrand Sure. I was just making sure that we won't be obstacle to users, if they want to create a methods with the same name.

**Comment by tbrand** [comment]
Thanks for the great commit!

**Review by tbrand — APPROVED** [review]

**Pull request merged**
